#!/usr/bin/env php

<?php

$autoloadPaths = [
	__DIR__ . '/vendor/autoload.php',
	__DIR__ . '/../../autoload.php'
];

foreach ($autoloadPaths as $path) {
	if (file_exists($path)) {
		require_once $path;
		break;
	}
}

require __DIR__ . '/src/Helper/Log.php';
require __DIR__ . '/src/Helper/Path.php';
require __DIR__ . '/src/TestRunner.php';

PWTest\Helper\Log::$level = 3;

$testRunner = new PWTest\TestRunner(getcwd());
$success = $testRunner->run();

if (! $success) {
	exit(1);
}