#!/usr/bin/env php
<?php

$autoloadPaths = [
	__DIR__ . '/vendor/autoload.php',
	__DIR__ . '/../../autoload.php'
];

foreach ($autoloadPaths as $path) {
	if (file_exists($path)) {
		require_once $path;
		break;
	}
}

use Tense\Application;

$application = new Application();
$application->run();